### ISSUE TITLE
Typescript typing umbrella issue

### ISSUE THREAD

**Issue by rricard** [apollographql/apollo-codegen#139]
Our goal ultimately is to get this whole codebase under typescript so we can code with some peace of mind!

We have this umbrella issue so we can split up the typing under smaller PRs:

- [x] #132 started the TS compatibility
- [x] #138 introduced a few files to TS
- [ ] IR/compilation
- [ ] Code Generation
- [ ] Misc core modules left
- [ ] Swift
- [ ] TS
- [ ] Flow

**Comment by jtmthf** [comment]
@rricard I restarted work recently on converting this codebase to TypeScript and noticed that you've been working on that as well. I have my changes in my [fork](https://github.com/jtmthf/apollo-codegen/tree/typescript) and currently have all of core except for compilation converted. Additionally I added TSLint and have been working on fixing linter issues simultaneously.

For now my version doesn't compile due to typings issues in `yargs` and `graphql`. I'll be filing PR's on their typings soon to remedy that issue.

Let me know if there's some good way we can divide and conquer the workload.

**Comment by rricard** [comment]
@jtmthf if you did not rebase yet, I would hold off on working on this. This repo will be refactored very soon. We'll try to obviously use TS while doing it but we won't just transfer the existing code to TS...
